apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-solr-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-solr
    {{- include "sitecore-solr.labels" . | nindent 4 }}
data:
  SOLR_JAVA_MEM: {{ .Values.solr.javaMemory | quote }}
  SOLR_MAX_FIELDS: "3000"
  SOLR_OPTS: "-Dsolr.modules=jwt-auth"
