apiVersion: v2
name: solr-prod
description: Sitecore Solr (Prod) — 3 Solr + 3 ZooKeeper
type: application
version: 0.1.0
appVersion: "8.11.2"
dependencies:
  - name: solr-base
    version: "0.1.0"
    repository: "file://../solr-base"
