apiVersion: batch/v1
kind: Job
metadata:
  name: solr-init
  namespace: solr
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: solr-init
          image: solr-init:local
          imagePullPolicy: Never
          env:
            - name: SOLR_URL
              value: "https://sitecore-solr-solrcloud-common.solr"
          volumeMounts:
            - name: collections-config
              mountPath: /init/collections.yml
              subPath: collections.yml
      volumes:
        - name: collections-config
          configMap:
            name: solr-collections-config
